# Test 2025-11-16 at 23:15:36

name: Test
run-name: silicon_compiler_mod_A_in_mod_B

on:
  push:
    paths:
      - '**/run.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Silicon compiler in a docker container
      run: |
        pwd
        ls -la
        docker run --rm -v "$(pwd):/app" ghcr.io/philiprbrenan/silicon_compiler_docker_image_asic:latest bash -x run.sh

    - name: Upload all files as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results
        path: .
        retention-days: 32
