# Test 2025-11-05 at 20:02:04

name: Test
run-name: silicon_compiler_mod_A_in_mod_B

on:
  push:
    paths:
      - '**/run.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Silicon compiler in a docker container
      run: |
        docker run --rm -v "$(pwd):/opt" ghcr.io/philiprbrenan/silicon_compiler_docker_image:0890fa2e60d6322611358f53bf1ff0d9b5e53926 python3 top.py

    - name: Upload all files as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results
        path: .
        retention-days: 32
