# Test 2025-11-17 at 00:28:41

name: Test
run-name: silicon_compiler_mod_A_in_mod_B

on:
  push:
    paths:
      - '**/run.yml'

  workflow_dispatch:
    inputs:
      moduleA:
        description: "Name of the top level module"
        required: true
        default: "top"
      moduleB:
        description: "Name of the child module"
        required: true
        default: "child"
      doPlace:
        description: "Enable placement step"
        required: false
        default: "yes"

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Silicon compiler in a docker container
      run: |
        pwd
        ls -la
        docker run --rm -v "$(pwd):/app" ghcr.io/philiprbrenan/silicon_compiler_docker_image_asic:latest bash -x run.sh

    - name: Upload all files as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results
        path: .
        retention-days: 32
