# Test 2025-11-05 at 21:14:23

name: Test
run-name: silicon_compiler_mod_A_in_mod_B

on:
  push:
    paths:
      - '**/run.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Silicon compiler in a docker container
      run: |
        pwd
        ls -la
        docker run --rm -v "$(pwd):/opt/siliconcompiler" ghcr.io/philiprbrenan/silicon_compiler_docker_image:2aa65c969630cd78c4e79b94aa6d95e1a6051faa bash -x run.sh

    - name: Upload all files as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results
        path: .
        retention-days: 32
